services:
  - type: web
    name: interview-scheduler
    env: python
    plan: free
    buildCommand: >
      pip install --upgrade pip setuptools wheel &&
      pip install --no-build-isolation -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true